import { Inter, Open_Sans } from 'next/font/google';
import './globals.css';
import { ClientProvider } from './ClientProvider';
import FacebookSDK from '@/components/Hook/facebookSKD';

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-inter',
});
const open_sens = Open_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-open_sens',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${open_sens.variable} antialiased `}>
        <FacebookSDK />
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
